trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: build
    displayName: build
    jobs:
      - template: ./cicd/build.yml
        parameters:
          name: build
          displayName: build web app