parameters:
- name: registryName
  type: string
- name: serviceConnection
  type: string
- name: resourceGroupName
  type: string

stages:

- stage: Validate_Shared_Infrastructure
  displayName: Validate Shared Infrastructure
  jobs:
  - job: ValidateBicepCode
    displayName: Validate Bicep code
    steps:
      - task: AzureCLI@2
        name: RunPreflightValidation
        displayName: Run preflight validation
        inputs:
          azureSubscription: $(ServiceConnection)
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment group validate \
              --resource-group $(ResourceGroupName) \
              --template-file deployment/sharedinfratructure.bicep \
              --parameters registryName=${{parameters.registryName}}

- stage: Deploy_Shared_Infrastructure
  displayName: Deploy Shared Infrastructure
  jobs:
  - deployment: DeployInfrastructure
    displayName: Deploy Infrastructure
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: AzureCLI@2
              name: DeployBicepFile
              displayName: Deploy Bicep file
              inputs:
                azureSubscription: $(ServiceConnection)
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  set -e
                  deploymentOutput=$(az deployment group create \
                    --name $(Build.BuildNumber) \
                    --resource-group $(ResourceGroupName) \
                    --template-file deployment/sharedinfratructure.bicep \
                    --parameters registryName=${{parameters.registryName}}