parameters:
- name: environmentType
  type: string

stages:

- ${{ if eq(parameters.environmentType, 'dev') }}:
  - stage: Validate_${{ parameters.environmentType }}
    displayName: Validate (${{ parameters.environmentType }} environment)
    condition: succeeded()
    jobs:
    - job: ValidateBicepCode
      displayName: Validate Bicep code
      steps:
        - task: AzureCLI@2
          name: RunPreflightValidation
          displayName: Run preflight validation
          inputs:
            azureSubscription: Blinkey-Subscription
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment group validate \
                --resource-group rg-blinkey-${{ parameters.environmentType }}-norwayeast-001 \
                --template-file deployment/blinkey.bicep \
                --parameters environmentType=${{ parameters.environmentType }} \
                             deploymentId=$(Build.BuildNumber)

- stage: Deploy_${{ parameters.environmentType }}
  displayName: Deploy (${{ parameters.environmentType }} Infrastructure)
  condition: succeeded()
  jobs:
  - deployment: DeployInfrastructure
    displayName: Deploy Infrastructure
    ${{ if eq(parameters.environmentType, 'dev') }}:
      environment: 'Blinkey development'
    ${{ else }}:
      environment: 'Blinkey production'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: AzureCLI@2
              name: DeployBicepFile
              displayName: Deploy Bicep file
              inputs:
                azureSubscription: Blinkey-Subscription
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment group create \
                    --name $(Build.BuildNumber) \
                    --resource-group rg-blinkey-${{ parameters.environmentType }}-norwayeast-001 \
                    --template-file deployment/blinkey.bicep \
                    --parameters environmentType=${{ parameters.environmentType }} \
                                 deploymentId=$(Build.BuildNumber)