trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - doc/*
      - README.md    

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerImageNameAndTag: 'blinkey:$(Build.BuildNumber)'
  containerRegistryName: 'crblinkeyshared001'

stages:

# Build and test web app
# - stage: Build
#   displayName: Build and test web app
#   jobs:
#     - template: templates/build.yml

# Linting the deployment script
- stage: Lint
  displayName: Linting the deployment file(s)
  jobs:
    - template: templates/lint.yml

# Deploy dev environment
- template: templates/deployInfrastructure.yml
  parameters:
    environmentType: dev
    containerRegistryName: $(containerRegistryName)
    dockerImageNameAndTag: $(dockerImageNameAndTag)

# Test, build and push container image
- stage: Push-image
  displayName: Build and push image
  jobs:
    - template: templates/DockerImage.yml
      parameters:
        dockerImageNameAndTag: $(dockerImageNameAndTag)
        containerRegistry: $(containerRegistryName)

# Deploy prod environment
- template: templates/deployInfrastructure.yml
  parameters:
    environmentType: prod
    containerRegistryName: $(containerRegistryName)
    dockerImageNameAndTag: $(dockerImageNameAndTag)