trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    exclude:
      - doc/*
      - README.md    

pool:
  vmImage: 'ubuntu-latest'

variables:
  webAppName: BlinkeyWebbApp
  dockerImageNameAndTag: 'blinkey:$(Build.BuildNumber)'
  containerRegistryName: 'crblinkeyshared001'
  serviceConnectionShared: 'Blinkey-shared'
  sharedResourceGroupName: 'rg-blinkey-shared-norwayeast-001'

stages:

# Build and test web app
# - stage: Build
#   displayName: Build and test web app
#   jobs:
#     - template: templates/build.yml

# Linting the deployment script
- stage: Lint
  displayName: Linting the deployment file(s)
  jobs:
    - template: templates/lint.yml

# Deploy dev environment
- template: templates/deployInfrastructure.yml
  parameters:
    environmentType: dev

# Deploy prod environment
- template: templates/deployInfrastructure.yml
  parameters:
    environmentType: prod

# Test, build and deploy container web app
- stage: Deploy_Webapp
  displayName: Deploy web app
  jobs:
    - template: templates/deployWebApp.yml
      parameters:
        dockerImageName: 'blinkey'
        containerRegistry: 'crblinkeyshared001'